### ISSUE TITLE
Only sidebar is printed while trying to knit to PDF

### ISSUE THREAD

**Issue by Debd8** [rstudio/pagedown#213] opened 2021-02-07 00:43 UTC
I'm trying to create a PDF resume with `chrome_print()` but it's only printing the sidebar and not the main body. 

The code I'm using:

```
---
title: "title"
author: "author"
output:
  pagedown::html_resume:
    self_contained: false
knit: pagedown::chrome_print
---
```
```
{css, echo=FALSE}

:root {
  --root-font-size: 11pt;
}

.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```
Aside of that, I'm also getting this warning:

```
Warning: A runtime exception has occured in Chrome
  Runtime exception message:
    TypeError: Cannot read property 'querySelectorAll' of null
```

I'm using a Google Chrome version `88.0.4324.150`, R version `3.6.3` and pagedown version `0.13.10`.

**Comment by cderv** [comment] 2021-02-08 09:10
Hi @Debd8, 

I cannot reproduce this using the R Markdown template for `html_resume` and adding your CSS chunk. 
I correctly got a PDF printed with no sidebar on the second page.

I have 88.0.4324.150, **pagedown** 0.13.10 too but R 4.0.3. 

Can you share a reproducible example of the issue we can run on our side ?

**Comment by Debd8** [comment] 2021-02-10 02:19
Hi @cderv,

Thanks for looking into the issue. Just to clarify I'm able to generate a PDF but with a blank main body.

A reproducible example below:

```
---
title: "title"
author: "author"
output:
  pagedown::html_resume:
    self_contained: false
knit: pagedown::chrome_print
---
```
```
{css, echo=FALSE}

:root {
  --root-font-size: 11pt;
}

.pagedjs_page:not(:first-of-type) {
  --sidebar-width: 0rem;
  --sidebar-background-color: #ffffff;
  --main-width: calc(var(--content-width) - var(--sidebar-width));
  --decorator-horizontal-margin: 0.2in;
}
```
```
Aside
================================================================================

Contact Info {#contact}
--------------------------------------------------------------------------------

- <i class="fas fa-envelope"></i> myemail@gmail.com


Skills {#skills}
--------------------------------------------------------------------------------

- Github

================================================================================

Debarati Dutta {#title}
--------------------------------------------------------------------------------


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Data Scientist

[XYZ Company]

Canada
```
Attached is the output PDF 
[resume_issue213.pdf](https://github.com/rstudio/pagedown/files/5955485/resume_issue213.pdf)

I have also updated my R version to `4.0.3` if that matters.

**Comment by Debd8** [comment] 2021-02-10 23:58
Works perfectly now. Thanks so much. What a silly error!!!

**Comment by cderv** [comment] 2021-02-11 10:34
This is often the more obvious that we don't see! I often get bitten by a typo in YAML header or wrong indentation and spend so many times looking deeper from what could go wrong... 🤦 

Glad it works now ! I'll close this.

**Closed by cderv** 2021-02-11 10:34 UTC
Labels: question
