### ISSUE TITLE
Pages in toc are all 1

### ISSUE THREAD

**Issue by petermeissner** [rstudio/pagedown#46] opened 2019-01-04 19:39 UTC
I have a simple markdown file like .Rmd-file like this: 

```markdown
---
output:
  pagedown::html_paged: 
    toc: true
    number_sections: false
  html_document: default
---

[...]
```

## The Problem

... all toc items get the same page ("1"). 

I get this error with Rstudio-Viewer and with Chrome. I do not get it with Firefox and rendering comletely fails with Edge. 

## Session Info

```
devtools::session_info()
- Session info -------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  German_Germany.1252         
 ctype    German_Germany.1252         
 tz       Europe/Berlin               
 date     2019-01-04                  

- Packages -----------------------------------------------------------------------------------------------------------------------------------------
 package     * version    date       lib source        
 assertthat    0.2.0      2017-04-11 [1] CRAN (R 3.5.1)
 backports     1.1.2      2017-12-13 [1] CRAN (R 3.5.0)
 callr         3.1.0      2018-12-10 [1] CRAN (R 3.5.1)
 cli           1.0.1      2018-09-25 [1] CRAN (R 3.5.1)
 crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)
 desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.1)
 devtools      2.0.1      2018-10-26 [1] CRAN (R 3.5.1)
 digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)
 fs            1.2.6      2018-08-23 [1] CRAN (R 3.5.1)
 glue          1.3.0      2018-07-17 [1] CRAN (R 3.5.1)
 magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)
 memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.1)
 pagedown    * 0.1        2019-01-02 [1] CRAN (R 3.5.1)
 pkgbuild      1.0.2      2018-10-16 [1] CRAN (R 3.5.1)
 pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.1)
 prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)
 processx      3.2.1      2018-12-05 [1] CRAN (R 3.5.1)
 ps            1.2.1      2018-11-06 [1] CRAN (R 3.5.1)
 R6            2.3.0      2018-10-04 [1] CRAN (R 3.5.1)
 Rcpp          1.0.0      2018-11-07 [1] CRAN (R 3.5.1)
 remotes       2.0.2      2018-10-30 [1] CRAN (R 3.5.1)
 rlang         0.3.0.1    2018-10-25 [1] CRAN (R 3.5.1)
 rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)
 rstudioapi    0.8        2018-10-02 [1] CRAN (R 3.5.1)
 sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.1)
 testthat      2.0.1      2018-10-13 [1] CRAN (R 3.5.1)
 usethis       1.4.0.9000 2018-12-20 [1] local         
 withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)

[1] C:/Users/peter/R/win-library/3.5
[2] C:/Program Files/R/R-3.5.1/library
```

**Comment by yihui** [comment] 2019-01-04 19:43
Duplicate of #35

**Closed** 2019-03-23 22:52 UTC
