### ISSUE TITLE
Cannot find headless Chrome after 20 attempts

### ISSUE THREAD

**Issue by gaowenxin95** [rstudio/pagedown#177] opened 2020-05-19 17:04 UTC
I use chrome_print to save a pdf, the html file is truely in the path ："file:///A/Gaowenxin_notes/le_pagedown/resume-gao.html",
```r
rmarkdown::render("resume-gao.Rmd")
pagedown::chrome_print(
    input = "file:///A/Gaowenxin_notes/le_pagedown/resume-gao.html",
    output = "output/cv-wenxin-gao.pdf",
    format = "pdf",
    timeout = 120
)
```
but l get this error，my system is win10,and R 3.6.2
```r
Error in is_remote_protocol_ok(debug_port, verbose = verbose) : 
  Cannot find headless Chrome after 20 attempts
```

**Comment by cderv** [comment] 2020-05-19 20:08
You can increase the maximum attempts if you wish using the `pagedown.remote.maxattempts` R option. 

Also can you use `verbose = TRUE` to get more information on the chrome connecting issue ? 

This error usually means that there is an issue with your chrome browser as pagedown does not succeed in connecting to the browser.

**Comment by gaowenxin95** [comment] 2020-05-30 01:13
```r
> pagedown::chrome_print(
+     input = "file:///A/Gaowenxin_notes/le_pagedown/resume-gao.html",
+     output = "output/cv-wenxin-gao.pdf",
+     format = "pdf",
+     timeout = 120,
+     verbose = TRUE
+ )
Using the browser "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
Trying to find headless Chrome in 20 attempts
Error in is_remote_protocol_ok(debug_port, verbose = verbose) : 
  Cannot find headless Chrome after 20 attempts
Closing browser
Cleaning browser working directory
```

**Comment by cderv** [comment] 2020-05-30 12:31
This error means that pagedown does manage to connect from R to the protocol as it does not seem to reach the browser. Maybe it is very long open or their is another issue in your environment.

Did you try to increase the number of attempt using the option or sleep time between attempt ? 
```r
options(pagedown.remote.maxattempts=40) # number of attempt in total
options(pagedown.remote.sleeptime=2) # time in second between attempt
```

If is does not help, we will need to look at why your chrome browser does not open correctly in devtools mode.

**Comment by RLesur** [comment] 2020-05-30 13:04
@gaowenxin95 Are you behind a proxy?

**Comment by RLesur** [comment] 2021-05-01 16:45
@gaowenxin95 Is this issue still active?

**Comment by iamericfletcher** [comment] 2022-09-18 18:01
> This error means that pagedown does manage to connect from R to the protocol as it does not seem to reach the browser. Maybe it is very long open or their is another issue in your environment.
> 
> Did you try to increase the number of attempt using the option or sleep time between attempt ?
> 
> ```r
> options(pagedown.remote.maxattempts=40) # number of attempt in total
> options(pagedown.remote.sleeptime=2) # time in second between attempt
> ```
> 
> If is does not help, we will need to look at why your chrome browser does not open correctly in devtools mode.

Please note that this solution worked for me in troubleshooting the identical issue described by the original author. 

I added the following to `render_cv.r` 
```
options(pagedown.remote.maxattempts=40) # number of attempt in total
options(pagedown.remote.sleeptime=2) # time in second between attempt
```

**Comment by cderv** [comment] 2022-09-19 08:47
Thank you for sharing. This confirms that this solves it. 

I'll close this. If more people have issues, we could increase the default, but it is easy enough for a user to add new defaults in R profile for this.

**Closed by cderv** 2022-09-19 08:47 UTC

**Comment by sanghoonio** [comment] 2023-03-09 21:06
Hello, I have this issue on a work laptop on Windows. I am behind a proxy and have tried the suggestions here. find_chrome() does return 
`> find_chrome()
                                                         (Default)2 
"C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe" `

but this continues to be my chrome_print() result:
`Using the browser "C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
Trying to find headless Chrome in 40 attempts
Error in is_remote_protocol_ok(debug_port, verbose = verbose) : 
  Cannot find headless Chrome after 40 attempts
Closing browser
Cleaning browser working directory`

**Comment by ashwinikalantri** [comment] 2023-05-21 21:07
I have exactly the same issue. What is peculiar is that one user on our rstudio server can use and print PDFs, while the other gets this error. 

> This error means that pagedown does manage to connect from R to the protocol as it does not seem to reach the browser. Maybe it is very long open or their is another issue in your environment.
> 
> Did you try to increase the number of attempt using the option or sleep time between attempt ?
> 
> ```r
> options(pagedown.remote.maxattempts=40) # number of attempt in total
> options(pagedown.remote.sleeptime=2) # time in second between attempt
> ```
> 
> If is does not help, we will need to look at why your chrome browser does not open correctly in devtools mode.

This doesn't help. @cderv how do I check why the browser doesn't open?

**Comment by sanghoonio** [comment] 2023-05-22 12:51
Unrelated solution, but check if the 'websocket' package is installed. I had this same issue and it resolved itself when I installed the package.

**Comment by JaydenCole-55** [comment] 2023-08-18 16:25
Hello,

I am running into the same problem mentioned in this issue's title. However, we are running into stack limit issues after headless google chrome is connected while the pdf stream is being read back. See attached image for more details.

Previously, we have been running `pagedown::chromeprint()` without issue, pagenating approximately 36, 37, or 38 page long documents. The problem occurs on MacOS Ventura 13.4.1(c) with stack size from `ulimit -s` as `8192`. The same code runs perfectly on a Windows 10 laptop. 

Have you any advice to have Pagedown use less stack size? Can it read the pdf back in smaller chunks? From what I understand, the pdf stream is too long for the available stack size limit on the Mac and is causing the error.

Thank you. 

<img width="1440" alt="MicrosoftTeams-image" src="https://github.com/rstudio/pagedown/assets/59719149/8f697e07-efd2-4b33-92d7-54d7df4e414c">

**Comment by JaydenCole-55** [comment] 2023-08-18 17:11
Following up on my previous comment, restarting the Mac computer did not fix the issue immediately on the latest code we had written. Our team then tried going back through our git history to a previous commit that had worked. The page down process was successful. Doing so iteratively to the newest commit showed that page down worked for every commit. This is not an issue with page down, but something to do with the allocated system resources on the Mac computer.

Thanks!

**Comment by radu-nicoara-bayer** [comment] 2024-04-11 08:46
Can you try to run this command in your terminal?
It should show you the entire error:
`google-chrome --headless --print-to-pdf=/tmp/test.pdf https://www.how2shout.com/`

**Comment by daviewales** [comment] 2024-10-11 03:11
If you are getting this on Ubuntu in October 2024, it's because the latest update to snap is broken on systems with LDAP users:

- https://askubuntu.com/questions/1529284/snap-is-throwing-an-authorization-exception
- https://bugs.launchpad.net/snapd/+bug/2083890

Options are to either revert to a previous version of `snapd`, or if you are viewing this from the future, to upgrade to a newer version of `snapd`. There is a fix apparently in the beta for snapd 2.66.
The last working version is snapd 2.63.

**Comment by royfrancis** [comment] 2024-10-21 17:19
Suddenly getting this error in Github actions. It used to be working fine.

**Comment by cderv** [comment] 2024-10-22 12:38
> Suddenly getting this error in Github actions. It used to be working fine.

As Google Chrome version change on github action ? 

> The same container works fine when running locally on a Mac.

Same container locally with docker as when running in docker on GHA ? This looks like some issues on GHA environment itselfs trying to connect to chrome remotely there. 😞

**Comment by royfrancis** [comment] 2024-10-22 14:00
Now I have created a minimal reproducible example. Here is the [repo](https://github.com/royfrancis/test-chromeprint/). You can see the error message in the [Actions log](https://github.com/royfrancis/test-chromeprint/actions/runs/11461595593/job/31891162458).

To describe what I have (for future when that repo link is broken). I have a dockerfile where I start with `ghcr.io/rocker-org/verse:4.4.1` and added google-chrome and pagedown. Then I use this to convert an RMD (xaringan) to HTML and then HTML to PDF. This works on my Mac M2 Sonoma and on my Linux machine running Ubuntu 20.04.

It fails on Github Pages with the error:

```
Error in is_remote_protocol_ok(debug_port, verbose = verbose) : 
  Cannot find headless Chrome after 20 attempts
Calls: <Anonymous> -> is_remote_protocol_ok
Execution halted
```

I have tried changing the runner from ubuntu-latest to ubuntu-20.04, I have tried changing the image base from verse:4.4.1 to verse:4.2. None of these have worked. 

So far I haven't tried downgrading or controlling google chrome version. It is possible that something has changed on GHA.

**Comment by cderv** [comment] 2024-10-22 15:22
The fact it works locally outside of GHA points to a environment-dependant problem. 

We have some new issues with latest chrome v130 on Windows but not report on unix. Quarto will use a version it is finding
https://github.com/quarto-dev/quarto-cli/blob/a2a22e5cd7d4ea5300b8f9ca1d094d998f2885f8/src/core/puppeteer.ts#L238-L241

But as it works in your container locally, it is seems puzzling it does not work on GHA. 

Anyhow, a newest issue it is best to open a new discussion. I don't know yet what to look for right now.

**Comment by daviewales** [comment] 2024-10-22 22:05
Probably good to try printing to PDF with Chrome directly as suggested in this comment:
https://github.com/rstudio/pagedown/issues/177#issuecomment-2049219330
That will tell you if it's a Chrome issue, or a pagedown issue.
