### ISSUE TITLE
Footnote in the TOC (html_paged)

### ISSUE THREAD

**Issue by pzhaonet** [rstudio/pagedown#54] opened 2019-01-26 22:19 UTC
It is exciting to start a new book with pagedown! Many thanks! I found a small issue: when footnotes are inserted in the chapter or section titles, they are supposed to appear only in the body. How could they avoid appearing at the bottom margins of the TOC pages?

Furthermore, it seems that the texts in the footnotes occupy some space in the TOC before rendered into the foot, resulting in large spaces in TOC pages.

An example could be found in my book; <https://www.pzhao.org/book/r100q/>

**Comment by pzhaonet** [comment] 2019-01-26 22:46
Thanks for the fast response. The Rmd source is here: <https://www.pzhao.org/book/r100q/r100q.rmd>. BTW, the page numbers of the titles with footnotes in TOC are wrong as well.

Please don't be too stressed about this issue. I don't think people often write books like this. Maybe footnotes in titles is not a good style. I will move them away from titles.

**Comment by pzhaonet** [comment] 2019-01-27 06:10
In case of the updates of my book, here is a screenshot showing the problems, including the wrong page number, the large blank area, and the footnotes which should appear only in the body rather than in TOC.

![2019-01-27-001](https://user-images.githubusercontent.com/4011804/51797365-52721d00-2202-11e9-894f-7deef43ed069.png)

**Comment by RLesur** [comment] 2019-01-27 07:11
- The wrong page numbers is a duplicate of #35 
- The large blank area is a side-effect of the experimental footnotes support we introduced in pagedown (paged.js does not support footnotes for now). The footnotes handler used in pagedown is a dirty hack and is far from perfect: I will write a technical post for pagedmedia.org to detail its mechanism and its side-effects. Introducing a native support in paged.js is on the roadmap of the paged.js project. However, it is a huge challenge from a technical point of view.  
- It would be easy to detect and remove footnotes in TOC. Would it be OK for you?

**Comment by jdbarillas** [comment] 2019-09-05 12:55
I'm running into the same issue of the footnote being in the TOC. What would be the easiest way to detect and remove it?

**Closed** 2019-09-05 18:01 UTC

**Comment by RLesur** [comment] 2019-09-05 18:06
@jdbarillas @pzhaonet I guess nobody wants duplicated footnotes in table of contents. 
I've pushed https://github.com/rstudio/pagedown/commit/e7d8b07caef91eea43f1af01b3e439e95def792a to remove them.

Sorry for the delay.
