### ISSUE TITLE
Issue with loft.lua during pandoc conversion

### ISSUE THREAD

**Issue by luzelai** [rstudio/pagedown#257] opened 2021-12-13 18:08 UTC
I tried to run the pagedown template, but it failed to compile in the end. This seems to be a problem with a lua script in pagedown. I have not tried pagedown on other systems, here is my code.

```
Error running filter /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library/pagedown/resources/lua/loft.lua:
[string "--[[..."]:123: Constructor for MetaInlines failed: [string "--[[..."]:166: attempt to call a nil value (field 'Str')

stack traceback:
	[C]: in function 'error'
	[string "--[[..."]:123: in field 'MetaInlines'
	...-arm64/Resources/library/pagedown/resources/lua/loft.lua:21: in function <...-arm64/Resources/library/pagedown/resources/lua/loft.lua:17>
Error: pandoc document conversion failed with error 83
Execution halted

```

**Comment by cderv** [comment] 2021-12-14 10:01
This issue is a duplicate of https://github.com/rstudio/pagedown/issues/245

You need to use the dev version of **pagedown** as I believe this issue has been solved in https://github.com/rstudio/pagedown/pull/249

We'll make a CRAN release soon.

**Comment by cderv** [comment] 2021-12-14 10:05
Duplicate of #245

**Closed** 2021-12-14 10:06 UTC
Labels: duplicate

**Comment by luzelai** [comment] 2021-12-14 10:51
Well, everything is OK after I installed the GitHub version.

Thank you for your great help!
